{
 "cells": [
  {
   "cell_type": "markdown",
   "id": "f18129ab",
   "metadata": {},
   "source": [
    "# Uso de Makefile para compilar, construir, ejecutar y probar programas C++\n",
    "\n",
    "- Makefile puede automatizar la tarea mundana de compilar, recompilar, probar e implementar programas C/C++.\n",
    "- Consulte el archivo Makefile.pre.in en [https://github.com/python/cpython](https://github.com/python/cpython) para ver cuán complicado puede ser Makefile para una gran base de software, como el lenguaje de programación Python escrito en C.\n",
    "- hay un excelente tutorial sobre Makefile: [https://makefiletutorial.com/](https://makefiletutorial.com/)\n",
    "- En este cuaderno demostraremos un Makefile muy simplificado para principiantes.\n",
    "- Hay 5 demostraciones simples proporcionadas en la carpeta `makefile_demos`\n",
    "- debe instalar el programa `make` en su sistema para usar Makefile\n",
    "    - en Linux, `make` suele estar preinstalado; de lo contrario, instálelo a través del administrador de paquetes\n",
    "        - en sistemas basados en Ubuntu/Debian, ejecute el comando `sudo apt install build-essential`\n",
    "    - en MacOS, instale las herramientas de línea de comandos de Xcode ejecutando el comando `xcode-select --install` en la Terminal\n",
    "    - en Windows, instale `make` a través del administrador de paquetes [Chocolatey](https://chocolatey.org/) ejecutando el comando `choco install make` desde un símbolo del sistema elevado o PowerShell\n",
    "\n",
    "## Estructura del archivo Makefile\n",
    "\n",
    "- Un Makefile consta de reglas con la siguiente estructura \n",
    "\n",
    "```Archivo MAKE\n",
    "# comentarios\n",
    "VARIABLE1 = valor1\n",
    "VARIABLE2 = valor2\n",
    "objetivo: dependencias\n",
    "    comando1 $(VARIABLE1)\n",
    "    comando2 $(VARIABLE2)\n",
    "    ...\n",
    "```\n",
    "\n",
    "- `destino`: suele ser el nombre del archivo generado por un programa; p.ej. archivo ejecutable u objeto\n",
    "- `dependencias`: son archivos que se utilizan como entrada para crear el objetivo; p.ej. archivos de código fuente\n",
    "- `comandos`: son comandos de shell utilizados para crear el objetivo a partir de las dependencias.\n",
    "- cada comando debe ir precedido de un carácter de tabulación (no espacios)\n",
    "- cuando ejecuta el comando `make target`, `make` comprobará si el archivo de destino existe y está actualizado con respecto a sus dependencias\n",
    "    - si el archivo de destino no existe o es más antiguo que cualquiera de sus dependencias, `make` ejecutará los comandos para crear o actualizar el archivo de destino\n",
    "    - si el archivo de destino está actualizado, `make` no hará nada\n",
    "\n",
    "## Usando el programa Crear\n",
    "- crear un archivo llamado `Makefile` dentro de la carpeta del proyecto\n",
    "- utilice la plantilla Makefile proporcionada en [makefile_demos/Makefile_template](./makefile_demos/Makefile_template)\n",
    "- ejecute los siguientes comandos desde dentro de la carpeta del proyecto en una Terminal\n",
    "\n",
    "```golpecito\n",
    "$ cd projectFolder # cambiar el director de trabajo actual - carpeta con archivos c++\n",
    "$ hacer # construir programa\n",
    "$ ls # ver el nombre de su ejecutable en el directorio actual\n",
    "$ ./programName # ejecuta el programa por su nombre\n",
    "$ hacer limpieza # ejecutar regla limpia; normalmente elimina todos los archivos object/exe\n",
    "```\n",
    "\n",
    "### Nota\n",
    "- Normalmente ejecutas comandos make desde Terminal\n",
    "- para demostración, usaremos Jupyter Notebook para ejecutar los comandos make\n",
    "    - Jupyter Notebook puede ejecutar comandos Bash con el símbolo `!` \n",
    "    - Se requiere Ipython Kernel para ejecutar los comandos mágicos que comienzan con `%` en el cuaderno Jupyter."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "f86048e4",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "/Users/rbasnet/projects/CPP-Fundamentals/notebooks\n"
     ]
    }
   ],
   "source": [
    "! pwd # print the current working directory"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "id": "32c0e7c0",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "/Users/rbasnet/projects/CPP-Fundamentals/notebooks/demos/makefiles\n"
     ]
    }
   ],
   "source": [
    "%cd demos/makefiles"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "id": "ee65f833",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Makefile_template \u001b[1m\u001b[36mdemo2\u001b[m\u001b[m             \u001b[1m\u001b[36mdemo4\u001b[m\u001b[m\n",
      "\u001b[1m\u001b[36mdemo1\u001b[m\u001b[m             \u001b[1m\u001b[36mdemo3\u001b[m\u001b[m             \u001b[1m\u001b[36mdemo5\u001b[m\u001b[m\n"
     ]
    }
   ],
   "source": [
    "! ls"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "id": "093c24b7",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "/Users/rbasnet/projects/CPP-Fundamentals/notebooks/demos/makefiles/demo1\n"
     ]
    }
   ],
   "source": [
    "%cd demo1"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 9,
   "id": "1acdfca9",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Makefile  hello.cpp\n"
     ]
    }
   ],
   "source": [
    "! ls"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "91f992f7",
   "metadata": {},
   "source": [
    "## Demostraciones de Makefile\n",
    "\n",
    "- La carpeta `demos/makefiles/` contiene 5 demostraciones simples de Makefile\n",
    "\n",
    "### demostración1 \n",
    "- tiene tres reglas simples\n",
    "- compilar, ejecutar y limpiar\n",
    "- los nombres de las reglas terminan con:\n",
    "    - puedes tener uno o más comandos asociados con la regla\n",
    "    - los comandos tienen tabulaciones\n",
    "    - Los comandos son típicamente comandos Bash que normalmente se ejecutan en la Terminal.\n",
    "- las reglas se llaman desde la Terminal usando la sintaxis:\n",
    "```golpecito\n",
    "hacer <nombre_regla>\n",
    "```\n",
    "\n",
    "- por ejemplo,\n",
    "```golpecito\n",
    "hacer correr\n",
    "```\n",
    "\n",
    "- mientras se ejecuta make, si no se llama a ningún nombre de regla, la primera regla se ejecuta de forma predeterminada"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 10,
   "id": "c853bd0e",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "# a simple Makefile with 3 rules\n",
      "\n",
      "# rule for compiling program\n",
      "# make or make compile triggers the following rule\n",
      "compile:\n",
      "\tg++ hello.cpp\n",
      "\n",
      "# rule for running programming\n",
      "# make run triggers the following rule\n",
      "run:\n",
      "\t./a.out\n",
      "\n",
      "# rule for clean up\n",
      "# make clean triggers the following rule\n",
      "clean:\n",
      "\trm -f a.out\n"
     ]
    }
   ],
   "source": [
    "! cat Makefile"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "id": "fcc915c3",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "g++ hello.cpp\r\n"
     ]
    }
   ],
   "source": [
    "! make # run make compile, the first rule by default"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "id": "f6c37aac",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Makefile  \u001b[31ma.out\u001b[m\u001b[m     hello.cpp\r\n"
     ]
    }
   ],
   "source": [
    "! ls"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 9,
   "id": "0f3b1db0",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "./a.out\r\n",
      "Hello World!\r\n"
     ]
    }
   ],
   "source": [
    "! make run"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 12,
   "id": "0c56b69c",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "/Users/rbasnet/projects/CPP-Fundamentals/notebooks/demos/makefiles\n"
     ]
    }
   ],
   "source": [
    "%cd .."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 13,
   "id": "bca0f4eb",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "/Users/rbasnet/projects/CPP-Fundamentals/notebooks/demos/makefiles/demo5\n"
     ]
    }
   ],
   "source": [
    "%cd demo5"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "2fd72028",
   "metadata": {},
   "source": [
    "### demostración5\n",
    "- ejecutar Makefile desde la terminal\n",
    "- por alguna razón no se ejecuta desde Jupyter Notebook"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 14,
   "id": "e3557a77",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Makefile  hello.cpp\n"
     ]
    }
   ],
   "source": [
    "! ls"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 13,
   "id": "38c42012",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "# Farily complex Makefile demo\r\n",
      "\r\n",
      "COMPILER = clang++\r\n",
      "COMPILER_FLAGS = -c -g -Wall -std=c++17\r\n",
      "\r\n",
      "# list .cpp files separated by space\r\n",
      "CPP_FILES = hello.cpp\r\n",
      "\r\n",
      "# executable program name\r\n",
      "PROGRAM_NAME = hello.exe\r\n",
      "\r\n",
      "# rule using other rules\r\n",
      "# other rules must be written after the rule name on the same line separated by a space\r\n",
      "all: build run clean\r\n",
      "\t@echo \"All Done!\"\r\n",
      "\r\n",
      "\r\n",
      "# rule for compiling and building program\r\n",
      "# make or make all or make build triggers the following rule\r\n",
      "# @ suppreses/hides the command itself from printing\r\n",
      "build:\r\n",
      "\t@# compile .cpp to object file .o\r\n",
      "\t@echo \"compiling...\"\r\n",
      "\t$(COMPILER) $(COMPILER_FLAGS) $(CPP_FILES)\r\n",
      "\t@# build executable from object files\r\n",
      "\t@echo \"building...\"\r\n",
      "\t$(COMPILER) -o $(PROGRAM_NAME) *.o\r\n",
      "\r\n",
      "# rule for running binary program\r\n",
      "# make run triggers the following rule\r\n",
      "run:\r\n",
      "\t@echo \"running program...\"\r\n",
      "\t./$(PROGRAM_NAME)\r\n",
      "\r\n",
      "# rule for clean up\r\n",
      "# make clean triggers the following rule\r\n",
      "clean:\r\n",
      "\t@echo \"cleaning up...\"\r\n",
      "\t@rm -f $(PROGRAM_NAME) *.o *.out 2> /dev/null\r\n"
     ]
    }
   ],
   "source": [
    "! cat Makefile"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 16,
   "id": "4a11400f",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "compiling...\n",
      "clang++ -c -g -Wall -std=c++17 hello.cpp\n",
      "building...\n",
      "clang++ -o hello.exe *.o\n"
     ]
    }
   ],
   "source": [
    "! make build"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 17,
   "id": "bae690e2",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "running program...\n",
      "./hello.exe\n",
      "Hello World!\n"
     ]
    }
   ],
   "source": [
    "! make run"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 18,
   "id": "ed03059e",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Makefile  hello.cpp \u001b[31mhello.exe\u001b[m\u001b[m hello.o\n"
     ]
    }
   ],
   "source": [
    "! ls "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 19,
   "id": "eb86f1ee",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "cleaning up...\n"
     ]
    }
   ],
   "source": [
    "! make clean"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 20,
   "id": "c355ee4a",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Makefile  hello.cpp\n"
     ]
    }
   ],
   "source": [
    "! ls"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "5d3d1a3e",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "cpp",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.9.20"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}